apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: durgesh191/sample-html-app:v1.x
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/durgesh191_sample-html-app.update-strategy: semver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-html-app
  template:
    metadata:
      labels:
        app: sample-html-app
    spec:
      containers:
      - name: sample-html-app
        image: durgesh191/sample-html-app:v1.1.0
        ports:
        - containerPort: 80
