apiVersion: v1
kind: Service
metadata:
  name: html-app-service
spec:
  selector:
    app: sample-html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010
  type: NodePort